# Generated by Django 3.2.13 on 2022-07-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
